#' Calculates sensitivity of the imputation
#'
#' @param imputation An imputation object generated by imputer
#' @return A sensitivity value
#' @examples
#' imputation(imputation)
#' @export

impsens <- function(imputation){
  
  filtered_imputation <- imputation %>% 
    filter(observed == 1)
    
  TP <- sum(filtered_imputation$observed == 1 & filtered_imputation$imputed == 1)
  kFN <- sum(filtered_imputation$observed == 1 & filtered_imputation$imputed == 0)
  sensitivity <- TP / (TP + kFN) # Proportion of positives that were correctly imputed
  
  return(sensitivity)
}