#' Calculates partial recovery of the imputation
#'
#' @param imputation An imputation object generated by imputer
#' @return A sensitivity value
#' @examples
#' recovery(imputation)
#' @export

recovery <- function(imputation){
  
  filtered_imputation <- imputation %>% 
    filter(observed == 1)
    
  TP <- sum(filtered_imputation$observed == 1 & filtered_imputation$imputed == 1)
  kFN <- sum(filtered_imputation$observed == 1 & filtered_imputation$imputed == 0)
  recovery <- TP / (TP + kFN) # Proportion of positives that were correctly imputed
  
  return(recovery)
}